services:
  jira:
    image: artifactory.lab.eemilee.me/docker/jira:latest
    container_name: jira
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - home:/var/atlassian/application-data/jira
    networks:
      local:
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jira
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=password
      - ATL_PROXY_NAME=jira.lab.eemilee.me
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_PORT=8080
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: jira-db-postgres
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: password
      LANG: C.UTF-8
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=en-US --encoding=UTF8"
    volumes:
      - db:/var/lib/postgresql
    networks:
      local:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jira -d jira" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

networks:
  local:

volumes:
  db:
  home: