services:
  confluence:
    image: artifactory.lab.eemilee.me/docker/confluence:latest
    container_name: confluence
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8090:8090"
    volumes:
      - home:/var/atlassian/application-data/confluence
    networks:
      confluence:
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/confluence
      - ATL_DB_TYPE=postgresql
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=password
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: confluence-db-postgres
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: confluence
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      confluence:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U confluence -d confluence" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

networks:
  confluence:

volumes:
  db:
  home: