services:
  jfrog-artifactory:
    image: emilyyy0621/jfrog-artifactory:latest
    container_name: jfrog-artifactory
    environment:
      - SKIP_WAIT_FOR_EXTERNAL_DB=true
    ports:
      - "8082:8082"
    volumes:
      - home:/var/opt/jfrog/artifactory
    networks:
      local:
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: releases-docker.jfrog.io/postgres:17.6-alpine
    container_name: jfrog-artifactory-db-postgres
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      local:
    restart: always

volumes:
  db:
  home:

networks:
  local: