services:
  jfrog-artifactory:
    image: emilyyy0621/jfrog-artifactory:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == docker-vm1
    environment:
      - SKIP_WAIT_FOR_EXTERNAL_DB=true
    ports:
      - "8082:8082"
    volumes:
      - home:/var/opt/jfrog/artifactory
    networks:
      local:
    depends_on:
      - postgres

  postgres:
    image: releases-docker.jfrog.io/postgres:17.6-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == docker-master
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD_FILE=/run/secrets/artifactory-db-password
    secrets:
      - artifactory-db-password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      local:

volumes:
  db:
  home:

networks:
  local:
    driver: overlay

secrets:
  artifactory-db-password:
    external: true