[Interface]
PrivateKey = <cloud VM WireGuard private key>
Address = 10.0.0.1/24
ListenPort = 51820

PostUp = iptables -A FORWARD -i wg0 -j ACCEPT;
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT;

[Peer]
PublicKey = <local WireGuard public key>
AllowedIPs = 10.0.0.2/32