http:
  routers:
    portainer:
      rule: "Host(`portainer.lab.eemilee.me`)"
      entryPoints:
        - websecure
      service: portainer
      tls:
        certResolver: letsencrypt

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://192.168.0.121:9443"
        serversTransport: portainerTransport

  serversTransports:
    portainerTransport:
      insecureSkipVerify: true